# Builds the GLUT example program with MinGW.

CC = gcc.exe
CFLAGS = -Wall -O3 -I C:/MingW/include/GL
LFLAGS = -s -lfreeglut -lglu32 -lopengl32 -mwindows -Wl,-subsystem,console

all: maze.exe

%.exe: %.c
	$(CC) -o $@ $< $(CFLAGS) $(LFLAGS)
